experiment_name: "baseline"
model:
  name: "EfficientNetB0"
  pretrained: False
  num_classes: 10
train:
  batch_size: 32
  epochs: 30
  lr: 0.001
  optimizer: "Adam"
  scheduler: "CosineDecay"
data:
  input_size: [224, 224]
  augment: True