model:
  name: efficientnet          # 모델 이름 (필수)
  trainable: true             # backbone 학습 여부 (선택, 기본값 True)
  final_activation: softmax  # 출력층 활성화 함수 (선택, 기본 softmax)

  # 정규화 설정 (모두 선택적)
  regularizer:
    kernel:
      type: l2
      l2: 1e-4


  hidden_layers:
    - units: 256
      dropout: 0.5
      activation: relu
