compile:
  optimizer:
    name: adamw
    weight_decay: 1e-4
    scheduler: 
      type: cosine
      initial_learning_rate: 0.001
      decay_steps: 1000
      warmup:
        steps: 20
        initial_lr: 1e-6
