compile:
  optimizer:
    name: adamw
    weight_decay: 1e-4
    scheduler:
      type: cosine
      initial_learning_rate: 0.001
      decay_steps: 1000
      alpha: 0.0
      warmup:
        steps: 200
        initial_lr: 1e-6
